export const CATEGORY_OPTIONS = [
  { value: "POTHOLE", label: "Pothole" },
  { value: "ROAD_DAMAGE", label: "Road damage" },
  { value: "BROKEN_FOOTPATH", label: "Broken footpath" },
  { value: "ROAD_CRACK", label: "Road crack" },
  { value: "ROAD_BLOCKAGE", label: "Road blockage" },
  { value: "TRAFFIC_SIGNAL", label: "Traffic signal" },
  { value: "MISSING_ROAD_SIGN", label: "Missing road sign" },
  { value: "ILLEGAL_PARKING", label: "Illegal parking" },
  { value: "SPEED_BREAKER", label: "Speed breaker" },
  { value: "BRIDGE_DAMAGE", label: "Bridge damage" },
  { value: "STREETLIGHT", label: "Streetlight" },
  { value: "BROKEN_ELECTRIC_POLE", label: "Broken electric pole" },
  { value: "HANGING_ELECTRIC_WIRE", label: "Hanging electric wire" },
  { value: "POWER_LINE_HAZARD", label: "Power line hazard" },
  { value: "TRANSFORMER_ISSUE", label: "Transformer issue" },
  { value: "FLOODING", label: "Flooding" },
  { value: "DRAIN_BLOCKED", label: "Drain blocked" },
  { value: "DRAIN_OVERFLOW", label: "Drain overflow" },
  { value: "WATER_LEAKAGE", label: "Water leakage" },
  { value: "BROKEN_PIPELINE", label: "Broken pipeline" },
  { value: "WATER_SUPPLY", label: "Water supply" },
  { value: "GARBAGE_COLLECTION", label: "Garbage collection" },
  { value: "OVERFLOWING_DUSTBIN", label: "Overflowing dustbin" },
  { value: "ILLEGAL_DUMPING", label: "Illegal dumping" },
  { value: "MEDICAL_WASTE", label: "Medical waste" },
  { value: "DEAD_ANIMAL", label: "Dead animal" },
  { value: "OPEN_MANHOLE", label: "Open manhole" },
  { value: "DANGEROUS_CONSTRUCTION", label: "Dangerous construction" },
  { value: "FALLEN_TREE", label: "Fallen tree" },
  { value: "TREE_TRIMMING", label: "Tree trimming" },
  { value: "FIRE_HAZARD", label: "Fire hazard" },
  { value: "UNSAFE_BUILDING", label: "Unsafe building" },
  { value: "BROKEN_BOUNDARY_WALL", label: "Broken boundary wall" },
  { value: "PARK_MAINTENANCE", label: "Park maintenance" },
  { value: "BROKEN_PLAYGROUND", label: "Broken playground" },
  { value: "PUBLIC_TOILET", label: "Public toilet" },
  { value: "DAMAGED_BENCH", label: "Damaged bench" },
  { value: "DAMAGED_BUS_STOP", label: "Damaged bus stop" },
  { value: "BROKEN_STREET_SIGN", label: "Broken street sign" },
  { value: "MISSING_ROAD_DIVIDER", label: "Missing road divider" },
  { value: "BROKEN_RAILING", label: "Broken railing" },
  { value: "DAMAGED_PUBLIC_PROPERTY", label: "Damaged public property" },
  { value: "GAS_LEAK", label: "Gas leak" },
  { value: "SEWERAGE_PROBLEM", label: "Sewerage problem" },
  { value: "CABLE_HAZARD", label: "Cable hazard" },
  { value: "MOSQUITO_BREEDING", label: "Mosquito breeding" },
  { value: "BAD_ODOR", label: "Bad odor" },
  { value: "AIR_POLLUTION", label: "Air pollution" },
  { value: "WATER_POLLUTION", label: "Water pollution" },
  { value: "NOISE_POLLUTION", label: "Noise pollution" },
  { value: "STRAY_DOG", label: "Stray dog" },
  { value: "INJURED_ANIMAL", label: "Injured animal" },
  { value: "OTHER", label: "Other" },
];

export function getCategoryLabel(value) {
  const match = CATEGORY_OPTIONS.find((item) => item.value === value);
  return match ? match.label : value || "Other";
}
